<?php
/**
 * Company: InfyOm Technologies, Copyright 2019, All Rights Reserved.
 * Author: Vishal Ribdiya
 * Email: vishal.ribdiya@infyom.com
 * Date: 29-07-2019
 * Time: 12:39 PM.
 */

namespace Tests\Integration;

use Tests\Models\MyTable;
use Tests\TestCase;

/**
 * Class TestAPITest.
 */
class MyTableAPIControllerTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function test_can_get_all_records()
    {
        $myTables = factory(MyTable::class)->times(3)->create();

        $result = $this->get('my-tables');
        $this->assertTrue($result->original['success']);
        $this->assertCount(3, $result->original['data']);
    }

    /** @test */
    public function test_can_get_only_specific_records()
    {
        $myTables = factory(MyTable::class)->times(3)->create();

        $result = $this->get('my-tables?field1_id='.$myTables[0]->field1_id);

        $this->assertCount(1, $result->original['data']);
        $this->assertEquals($myTables[0]->id, $result->original['data'][0]['id']);
    }
}
